#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlytaisan
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IT_Test")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQuanlytaisan(Quanlytaisan instance);
    partial void UpdateQuanlytaisan(Quanlytaisan instance);
    partial void DeleteQuanlytaisan(Quanlytaisan instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Quanlytaisan.Properties.Settings.Default.IT_TestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Quanlytaisan> Quanlytaisans
		{
			get
			{
				return this.GetTable<Quanlytaisan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Quanlytaisan")]
	public partial class Quanlytaisan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Data.Linq.Binary _anh;
		
		private string _stt;
		
		private string _mataisan;
		
		private string _tentaisan;
		
		private string _bophanquanly;
		
		private string _bophansudung;
		
		private string _nguoisudung;
		
		private string _nguoisudungtruoc;
		
		private string _thongtintaisan;
		
		private string _ngaykiemtra;
		
		private string _tinhtrangtaisan;
		
		private string _ghichu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnanhChanging(System.Data.Linq.Binary value);
    partial void OnanhChanged();
    partial void OnsttChanging(string value);
    partial void OnsttChanged();
    partial void OnmataisanChanging(string value);
    partial void OnmataisanChanged();
    partial void OntentaisanChanging(string value);
    partial void OntentaisanChanged();
    partial void OnbophanquanlyChanging(string value);
    partial void OnbophanquanlyChanged();
    partial void OnbophansudungChanging(string value);
    partial void OnbophansudungChanged();
    partial void OnnguoisudungChanging(string value);
    partial void OnnguoisudungChanged();
    partial void OnnguoisudungtruocChanging(string value);
    partial void OnnguoisudungtruocChanged();
    partial void OnthongtintaisanChanging(string value);
    partial void OnthongtintaisanChanged();
    partial void OnngaykiemtraChanging(string value);
    partial void OnngaykiemtraChanged();
    partial void OntinhtrangtaisanChanging(string value);
    partial void OntinhtrangtaisanChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    #endregion
		
		public Quanlytaisan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stt", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string stt
		{
			get
			{
				return this._stt;
			}
			set
			{
				if ((this._stt != value))
				{
					this.OnsttChanging(value);
					this.SendPropertyChanging();
					this._stt = value;
					this.SendPropertyChanged("stt");
					this.OnsttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mataisan", DbType="NVarChar(50)")]
		public string mataisan
		{
			get
			{
				return this._mataisan;
			}
			set
			{
				if ((this._mataisan != value))
				{
					this.OnmataisanChanging(value);
					this.SendPropertyChanging();
					this._mataisan = value;
					this.SendPropertyChanged("mataisan");
					this.OnmataisanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentaisan", DbType="NVarChar(50)")]
		public string tentaisan
		{
			get
			{
				return this._tentaisan;
			}
			set
			{
				if ((this._tentaisan != value))
				{
					this.OntentaisanChanging(value);
					this.SendPropertyChanging();
					this._tentaisan = value;
					this.SendPropertyChanged("tentaisan");
					this.OntentaisanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bophanquanly", DbType="NVarChar(50)")]
		public string bophanquanly
		{
			get
			{
				return this._bophanquanly;
			}
			set
			{
				if ((this._bophanquanly != value))
				{
					this.OnbophanquanlyChanging(value);
					this.SendPropertyChanging();
					this._bophanquanly = value;
					this.SendPropertyChanged("bophanquanly");
					this.OnbophanquanlyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bophansudung", DbType="NVarChar(50)")]
		public string bophansudung
		{
			get
			{
				return this._bophansudung;
			}
			set
			{
				if ((this._bophansudung != value))
				{
					this.OnbophansudungChanging(value);
					this.SendPropertyChanging();
					this._bophansudung = value;
					this.SendPropertyChanged("bophansudung");
					this.OnbophansudungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoisudung", DbType="NVarChar(50)")]
		public string nguoisudung
		{
			get
			{
				return this._nguoisudung;
			}
			set
			{
				if ((this._nguoisudung != value))
				{
					this.OnnguoisudungChanging(value);
					this.SendPropertyChanging();
					this._nguoisudung = value;
					this.SendPropertyChanged("nguoisudung");
					this.OnnguoisudungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoisudungtruoc", DbType="NVarChar(50)")]
		public string nguoisudungtruoc
		{
			get
			{
				return this._nguoisudungtruoc;
			}
			set
			{
				if ((this._nguoisudungtruoc != value))
				{
					this.OnnguoisudungtruocChanging(value);
					this.SendPropertyChanging();
					this._nguoisudungtruoc = value;
					this.SendPropertyChanged("nguoisudungtruoc");
					this.OnnguoisudungtruocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thongtintaisan", DbType="NVarChar(50)")]
		public string thongtintaisan
		{
			get
			{
				return this._thongtintaisan;
			}
			set
			{
				if ((this._thongtintaisan != value))
				{
					this.OnthongtintaisanChanging(value);
					this.SendPropertyChanging();
					this._thongtintaisan = value;
					this.SendPropertyChanged("thongtintaisan");
					this.OnthongtintaisanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaykiemtra", DbType="NVarChar(50)")]
		public string ngaykiemtra
		{
			get
			{
				return this._ngaykiemtra;
			}
			set
			{
				if ((this._ngaykiemtra != value))
				{
					this.OnngaykiemtraChanging(value);
					this.SendPropertyChanging();
					this._ngaykiemtra = value;
					this.SendPropertyChanged("ngaykiemtra");
					this.OnngaykiemtraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrangtaisan", DbType="NVarChar(50)")]
		public string tinhtrangtaisan
		{
			get
			{
				return this._tinhtrangtaisan;
			}
			set
			{
				if ((this._tinhtrangtaisan != value))
				{
					this.OntinhtrangtaisanChanging(value);
					this.SendPropertyChanging();
					this._tinhtrangtaisan = value;
					this.SendPropertyChanged("tinhtrangtaisan");
					this.OntinhtrangtaisanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(50)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
